apiVersion: v1
kind: Service
metadata:
  labels:
    app: a-spring
  name: a-spring
spec:
  ports:
  - name: a-spring
    port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: a-spring
  sessionAffinity: None
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: a-spring
  name: a-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-spring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: a-spring
    spec:
      containers:
      - image: master.cfc:8500/default/my-spring:v2
        imagePullPolicy: Always
        name: a-spring
        ports:
        - containerPort: 9080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: admin.registrykey